tp:
  multiplier: 0.1 # this value multiplies the distance of one player to another, the resulting amount will be the payment
  default_amount: 3  # default payment, the least amount that a player will pay